### ISSUE TITLE
How to get keypair.public_key to keypair._keypair.public_key?

### ISSUE THREAD

**Issue by CrackerHax** [michaelhly/solana-py#229]
What do I have to do to keypair.public_key to get it to == keypair._keypair.public_key?

I have to send it serialized (as keypair.public_key) and transform it back to the original nacl key (keypair._keypair.public_key) on the other end.

**Comment by CrackerHax** [comment]
I found if I do 

`base58.b58encode(bytes(keypair.public_key._key))`

it equals keypair.public_key

**Comment by crypt0miester** [comment]
can you explain what you want to do exactly? 

if I understand you correctly you would like the keypair from public_key? I don't think that is possible.

**Comment by CrackerHax** [comment]
I stated what I wanted to do in the initial post.

> can you explain what you want to do exactly?

**Comment by crypt0miester** [comment]
> I stated what I wanted to do in the initial post, exactly.
> 
> > can you explain what you want to do exactly?
> 
> 
> 
> 

alrighty then. good luck.

**Comment by CrackerHax** [comment]
Maybe I can try to clarify this for you... keypair._keypair.public_key is the nacl generated key and keypair.public_key is the derived key being used for solana. I want to know how to get the nacl key for a given solana address without referencing keypair._keypair.public_key. I don't know if I can be more clear than that...

**Comment by crypt0miester** [comment]
use nacl then.

```
import nacl
from solana.keypair import Keypair

key = Keypair()
raw_public_key = nacl.bindings.crypto_scalarmult_base(key.secret_key)
```

I feel like this is not what you are aiming for. Tell me your particular use case. I don't know if you can get the nacl PublicKey from the solana PublicKey. since solana PublicKey is a SigningKey rather than a PublicKey.

If you would like to verify a message from the public_key you would from js, you can use these:
python: https://gist.github.com/crypt0miester/6d4743403705f7c93de68d97d5d29b6f
js: https://gist.github.com/crypt0miester/ce0d10100aefa4e7352664b2de34df14

hope this helps

**Comment by CrackerHax** [comment]
I don't need to verify it, I need to be able to derive keys from it to use for encrypted messaging.

**Comment by kevinheavey** [comment]
This is out of date now since Keypair now uses solders instead of nacl
